schema: schema.graphql
extensions:
  endpoints:
    default:
      url: https://oscarbackend-production.up.railway.app/shop-api
      headers:
        Content-Type: application/json
      introspect: true
    production:
      url: ${NEXT_PUBLIC_GRAPHQL_URL}
      headers:
        Content-Type: application/json
