spring:

  # Development Database Configuration
  datasource:
    url: jdbc:postgresql://localhost:5432/oscar_ecommerce
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:majmajBS13..}

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

# GraphQL Configuration
graphql:
  spqr:
    gui:
      enabled: true
  playground:
    enabled: true
  voyager:
    enabled: true

# Logging
logging:
  level:
    root: INFO
    com.oscar.ecommerce: DEBUG
    org.hibernate.SQL: DEBUG
    org.springframework.security: WARN

# Enable all actuator endpoints in dev mode
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
